<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<html dir="ltr" lang="pt">

	<head>
	
		<title>
		</title>
		
		<meta name="keywords" content="" />
		<meta name="description" content="" />
		<meta name="robots" content="noindex, nofollow" />
		<meta http-equiv="content-language" content="br">
		<meta http-equiv="content-type" content="text/html; charset='windows-1252'" />

		<link rel="stylesheet" type="text/css" href="../../_include/classe.css" />
		
		<style type="text/css" media="all">
		</style>
		
		<script src="../../_include/funcoes.js"></script>
		<script src="../../_include/funcoes_aplicacao.js"></script>
		<script src="../../_include/executa_antes.js"></script>

		<script language="javascript">
			function fVoid_ConteudoAtualiza() {
				parent.document.getElementById('tag_conteudo').innerHTML = window.document.getElementById('tag_conteudo').innerHTML;
			}
		</script>

	</head>

	<body>
	
		<div id="tag_conteudo" name="tag_conteudo">
			<table border="0" cellpadding="0" cellspacing="0" width="100%" height="100%">
				<tr>
					<td width="50%" style="background-image: url(_imagem/img_fundo_conteudo_borda_vermelho_1.gif); background-position: top; background-repeat: repeat-x;">
					</td>
					<td style="background-image: url(_imagem/img_fundo_conteudo_borda_vermelho_2.gif); background-position: right top; background-repeat: no-repeat;">
						<div style="font-size: 0px; height: 23px; width: 23px;"></div>
					</td>
					<td style="background-image: url(_imagem/img_fundo_conteudo_borda_azul_3.gif); background-position: left; background-repeat: repeat-y;">
					</td>
					<td width="50%">
					</td>
				</tr>
				<tr height="100%">
					<td>
					</td>
					<td style="background-image: url(_imagem/img_fundo_conteudo_borda_vermelho_3.gif); background-position: right; background-repeat: repeat-y;">
					</td>
					<td style="background-image: url(_imagem/img_fundo_conteudo_borda_azul_3.gif); background-position: left; background-repeat: repeat-y;">
					</td>
					<td>
					</td>
				</tr>
				<tr>
					<td>
					</td>
					<td style="background-image: url(_imagem/img_fundo_conteudo_borda_vermelho_3.gif); background-position: right; background-repeat: repeat-y;">
					</td>
					<td style="background-image: url(_imagem/img_fundo_conteudo_borda_azul_2.gif); background-position: left bottom; background-repeat: no-repeat;">
						<div style="font-size: 0px; height: 23px; width: 23px;"></div>
					</td>
					<td style="background-image: url(_imagem/img_fundo_conteudo_borda_azul_1.gif); background-position: bottom; background-repeat: repeat-x;">
					</td>
				</tr>
			</table>
		</div>
	
		<script language="javascript">
			fVoid_ConteudoAtualiza();
		</script>
		<script src="_include/executa_depois.js"></script>

	</body>

</html>